# MicroManager Configuration Path
config_path = "C:\\Program Files\\Micro-Manager-2.0\\Ti2MightexCrestSolaSpectra_newlab3.cfg"

# SLM Configuration
affine_transform = [[  -0.29 ,  -0.002, 939.768], [   0.004,  -0.58 ,1505.944]]
slm_shape_h =  1140
slm_shape_w =  912
